### PR TITLE
linter fixes + aarch64 migration (as one PR)

### PR DESCRIPTION
**Pull request by dslarm**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dslarm** [comment]
@conda-forge-admin please rerender

**Comment by dslarm** [comment]
@conda-forge-admin please rerender
(prior build was cancelled, inexplicably)

**Comment by dslarm** [comment]
@conda-forge-admin please rerender

**Comment by dslarm** [comment]
@conda-forge-admin please rerender

**Comment by dslarm** [comment]
@cbrueffer  - this is ready to go, can you merge - it's (hopefully) a last dependency before I can enable another package in bioconda for linux-aarch64

**Review by martin-g — APPROVED** [review]
LGTM!

**Review by cbrueffer — APPROVED** [review]

**Pull request merged**
